# Generated by Django 2.0.2 on 2018-03-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_content',
            field=models.TextField(max_length=7000),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission_content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='value_content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision_content',
            field=models.TextField(max_length=2000),
        ),
    ]
